#+TITLE: Stadgar för IX
#+OPTIONS: toc:nil author:nil date:nil

* Förening
IX är en ideell ungdomsförening.

* Syfte
Föreningens syfte är att främja ungdomars intresse för datorer, naturvetenskap
och teknik. Att ge medemmarna möjlighet att öka förståelsen för dessa ämnens
betydelse i samhället samt att bruka kunskaperna inom relevanta områden.

* Obundenhet
Föreningen är religiöst och partipolitisk obunden.

* Verksamhets­ och räkenskapsår
Verksamhetsåret och räkenskapsåret omfattar tiden 1 januari till 31 december

* Medlemskap
Medlemskap kan erhållas av den som betalar eventuell medlemsavgift och
verkar enligt föreningens syfte. Om en medlem missköter sig eller skadar
föreningen kan personen uteslutas ur föreningen. Uteslutningen beslutas
av styrelsen och ska tas upp på årsmötet då den uteslutna har rätt att
yttra sig och det är årsmötet som slutligen bestämmer om uteslutningen
ska gälla eller hävas. Medlemskap måste förnyas varje kalenderår.

* Årsmöte
Årsmötet är föreningens högsta beslutande instans. Det ska hållas i
verksamhetsårets början, dock senast i mars månad. Årsmötet är beslutsmässigt
endast om skriftlig kallelse utgår senast fjorton dagar före mötet via brev
eller epost. Kallelsen ska skickas till alla medlemmar eller anslås så att alla
kan ta del av kallelsen. Möteshandlingar ska finnas medlemmarna tillhanda före
mötet. Tidpunkt och plats för mötet bestäms av styrelsen. Alla medlemmar är
röstberättigade vid årsmötet. Varje medlem har en röst och röstning genom
fullmakt är inte tillåten. Alla beslut fattas genom enkel majoritet utom frågan
om upplösning enligt §13. Vid årsmötet har ordförande, styrelse, revisorer och
medlemmar rätt att närvara, yttra sig samt lägga förslag. På årsmötet ska
följande punkter alltid behandlas:

 - Fråga om mötet är stadgeenligt kallat
 - Verksamhetsberättelse
 - Revisionsberättelse
 - Ekonomisk berättelse
 - Fråga om styrelsens ansvarsfrihet
 - Val av ordförande
 - Val av styrelseledamöter
 - Val av revisorer
 - Val av valberedning
 - Fastställande av medlemsavgift
 - Verksamhetsplan
 - Budget
 - Motioner
 - Övriga frågor

* Extra årsmöte
Extra årsmöte sammankallas om styrelsen eller minst en fjärdedel av medlemmarna
skriftligen begär det. Samma regler som för ordinarie årsmöte gäller men allt
som ska behandlas på mötet måste framgå i kallelsen.

* Styrelse
Styrelsen har sitt säte i Stockholm. Styrelsen ansvarar för den löpande
verksamheten och verkställer årsmötets beslut. Styrelsen väljs av årsmötet och
ska utöver ordförande bestå av tre (3) till åtta (8) ledamöter. Styrelsen
föredelar själv ledamöternas poster. Styrelsen ska sammanträda minst två gånger
per verksamhetsår. Styrelsen är beslutsmässig om kallelse utgått till samtliga
ledamöter och hälften av styrelsens ledamöter är närvarande.

* Föreningens firma
Styrelsen beslutar vem eller vilka som har rätt att teckna föreningens firma.

* Revisorer
Årsmötet väljer en revisor och en revisorssuppleant.

* Medlemsavgift
Eventuell medlemsavgift fastställs av årsmötet.

* Stadgeändring
Dessa stadgar kan ändras endast vid årsmöte eller extra årsmöte. I kallelsen
måste det stå att stadgeändring kommer att behandlas. För att andra i stadgarna
krävs att 2/3 av de avgivna rösterna bifaller ändringen. För ändring av stadgan
om Föreningens syfte §2, Stadgeändring §12 och Upplösning §13 krävs att beslutet
tas på två på varandra följande ordinarie årsmöten.

* Upplösning
Upplösning av föreningen kan endast ske genom beslut på ordinarie årsmöte med
2/3 majoritet. I kallelsen till årsmötet ska det stå att förlag om upplösning av
föreningen kommer att behandlas. Mötet beslutar om hur föreningens tillgångar
ska disponeras.
