#+TITLE: Styrelsemötesprotokoll
#+DATE: 2016-03-14
#+OPTIONS: toc:nil author:nil
#+LANGUAGE: sv
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper]
#+LATEX_HEADER: \usepackage[swedish]{babel}

* Mötets öppnande
Mötet öppnade klockan 17:45.

* Närvarande
Samtliga från styrelsen är närvarande.

* Val av mötesfunktionärer
Elis väljs som mötesordförande samt sekreterare.

* Punkter
** ix.ufs.se
UFS har beviljat att föreningen får en vidarebodring från http://ix.ufs.se/.
Elis har kontaktat Kotte för att få detta genomfört.

Den dagen som Github Pages implementerar Letsencrypt och ger TLS för custom
domäner så är det intressant att ha ett CNAME istället och faktiskt köra på det
domännamnet.

** Adressändring
Adressändring är gjort för att få vår post till UFS postbox och besöksadress
är ändrat till UFS lokal.

** VR Dator
Titta på Webhallens upgrade-kit för att köpa moderkort, RAM och CPU i en
bundle.

Detta ska dras igång direkt efter mötet.

** Logga
Inget nytt på denna punkt.

** Hemsida
Skriv mer oftare, fotagrafera gärna och lägg upp när det händer saker.

* Nästa möte
Nästa möte kommer vara den 4:e April 2016 klockan 19:00 i UFS lokal.

* Mötets avslutande
Mötet avslutas.

* Signaturer
** Sekreterare
\makebox[10cm]{\hrulefill}

** Justerare
\makebox[10cm]{\hrulefill}
